services:

  ecommerce-portfolio-backend:
    image: ecommerce-portfolio-backend
    expose:
      - 80
    networks:
      - postgresql_default
      - ecommerce-portfolio
    secrets:
      - DATABASE_URL
      - SECRET
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1/health || exit 1"]
      interval: 5m
      timeout: 5s
      retries: 5
      start_period: 10s

  ecommerce-portfolio-storefront:
    image: ecommerce-portfolio-storefront
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - ecommerce-portfolio
    secrets:
      - API_URL
      - SOURCE_GITHUB
      - PERSONAL_WEBSITE
    depends_on:
      ecommerce-portfolio-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:3000/ || exit 1"]
      interval: 5m
      timeout: 5s
      retries: 5
      start_period: 10s


networks:
  postgresql_default:
    external: true
  ecommerce-portfolio:

secrets:
  DATABASE_URL:
    file: ./.secrets/DATABASE_URL.txt
  SECRET:
    file: ./.secrets/SECRET.txt
  API_URL:
    file: ./.secrets/API_URL.txt
  SOURCE_GITHUB:
    file: ./.secrets/SOURCE_GITHUB.txt
  PERSONAL_WEBSITE:
    file: ./.secrets/PERSONAL_WEBSITE.txt

