services:

  ecommerce-portfolio-backend:
    extends:
      file: compose.yaml
      service: ecommerce-portfolio-backend
    

  ecommerce-portfolio-storefront:
    extends:
      file: compose.yaml
      service: ecommerce-portfolio-storefront
    networks:
      - nginx_default
    ports: !reset []
    volumes:
      - nginx_ecommerce_portfolio_volume:/app/.next/static


networks:
  nginx_default:
    external: true
  postgresql_default:
    external: true
  ecommerce-portfolio:


volumes:
  nginx_ecommerce_portfolio_volume:
    external: true

secrets:
  DATABASE_URL:
    file: ./.secrets/DATABASE_URL.txt
  SECRET:
    file: ./.secrets/SECRET.txt
  API_URL:
    file: ./.secrets/API_URL.txt
  SOURCE_GITHUB:
    file: ./.secrets/SOURCE_GITHUB.txt
  PERSONAL_WEBSITE:
    file: ./.secrets/PERSONAL_WEBSITE.txt
